build/crypto/test/poseidon/unit.compiled-test.js: crypto/test/poseidon/unit.compiled-test.js \
    crypto/poseidon.js crypto/modular.js \
    testing/assert.js testing/nodejs.js testing/nodejs.d.js
	bun birimler/js/compiler.js $^ -o $@
