build/crosschain/test/unlockable.compiled-test.js: crosschain/test/unlockable.compiled-test.js \
    crosschain/unlockable.d.js crosschain/unlockable.js \
    crosschain/signer.js \
    crypto/modular.js crypto/secp256k1.js \
    crypto/sha3.js \
    ethereum/eth.d.js ethereum/encryptedData.d.js ethereum/evm.js \
    testing/assert.js testing/nodejs.d.js \
    testing/vm.js testing/crosschain.js \
    util/çevir.js
	bun birimler/js/compiler.js $^ -o $@
