build/api/test/jsonrpc.compiled-test.js: api/test/jsonrpc.compiled-test.js \
    api/jsonrpc.d.js api/jsonrpc.js \
    crypto/sha3.js crypto/secp256k1.js crypto/modular.js \
    ethereum/evm.js \
    testing/assert.js testing/nodejs.d.js \
    util/çevir.js
	bun kdc/kdc.js $^ -o $@
