// Generated by `bun run css-types`. Do not edit by hand.

declare const Css: KastroStyleSheetComponent & {
  readonly "laal": string;
  readonly "laar": string;
  readonly "laasx": string;
  readonly "lacl": string;
  readonly "lacr": string;
  readonly "ladiv": string;
  readonly "laeq": string;
  readonly "laeqn": string;
  readonly "laeqni": string;
  readonly "lain": string;
  readonly "lamns": string;
  readonly "lapl": string;
  readonly "lapr": string;
  readonly "lasl": string;
  readonly "lasr": string;
  readonly "lassub": string;
  readonly "lassup": string;
  readonly "lasub": string;
  readonly "lasup": string;
  readonly "lasupsub": string;
  readonly "lato": string;
  readonly "law": string;
};

export default Css;
