import { Op } from "./opcodes";
import {
  Addr,
  Bool,
  Data,
  EvmType,
  Fragment,
  Locn,
  Size,
  Uint,
  Weis,
  Word,
} from "./types";

const op = (
  op: Op,
  expect: readonly EvmType[],
  ensure: readonly EvmType[] | null,
): Fragment => new Fragment(
  expect.slice().reverse(),
  ensure && ensure.slice().reverse(),
  expect.length,
  [op],
);

const Ops: Partial<Record<Op, Fragment>> = {
  [Op.STOP]: op(Op.STOP, [], null),
  [Op.ADD]: op(Op.ADD, [Uint, Uint], [Uint]),
  [Op.MUL]: op(Op.MUL, [Uint, Uint], [Uint]),
  [Op.SUB]: op(Op.SUB, [Uint, Uint], [Uint]),
  [Op.DIV]: op(Op.DIV, [Uint, Uint], [Uint]),
  [Op.SDIV]: op(Op.SDIV, [Uint, Uint], [Uint]),
  [Op.MOD]: op(Op.MOD, [Uint, Uint], [Uint]),
  [Op.SMOD]: op(Op.SMOD, [Uint, Uint], [Uint]),
  [Op.ADDMOD]: op(Op.ADDMOD, [Uint, Uint, Uint], [Uint]),
  [Op.MULMOD]: op(Op.MULMOD, [Uint, Uint, Uint], [Uint]),
  [Op.SIGNEXTEND]: op(Op.SIGNEXTEND, [Uint, Uint], [Uint]),
  [Op.LT]: op(Op.LT, [Uint, Uint], [Bool]),
  [Op.GT]: op(Op.GT, [Uint, Uint], [Bool]),
  [Op.SLT]: op(Op.SLT, [Uint, Uint], [Bool]),
  [Op.SGT]: op(Op.SGT, [Uint, Uint], [Bool]),
  [Op.EQ]: op(Op.EQ, [Word, Word], [Bool]),
  [Op.ISZERO]: op(Op.ISZERO, [Word], [Bool]),
  [Op.AND]: op(Op.AND, [Word, Word], [Word]),
  [Op.OR]: op(Op.OR, [Word, Word], [Word]),
  [Op.XOR]: op(Op.XOR, [Word, Word], [Word]),
  [Op.NOT]: op(Op.NOT, [Word], [Word]),
  [Op.BYTE]: op(Op.BYTE, [Uint, Word], [Uint]),
  [Op.SHL]: op(Op.SHL, [Uint, Uint], [Uint]),
  [Op.SHR]: op(Op.SHR, [Uint, Uint], [Uint]),
  [Op.SAR]: op(Op.SAR, [Uint, Uint], [Uint]),
  [Op.SHA3]: op(Op.SHA3, [Locn, Size], [Data]),
  [Op.ADDRESS]: op(Op.ADDRESS, [], [Addr]),
  [Op.BALANCE]: op(Op.BALANCE, [Addr], [Weis]),
  [Op.ORIGIN]: op(Op.ORIGIN, [], [Addr]),
  [Op.CALLER]: op(Op.CALLER, [], [Addr]),
  [Op.CALLVALUE]: op(Op.CALLVALUE, [], [Weis]),
  [Op.CALLDATALOAD]: op(Op.CALLDATALOAD, [Locn], [Data]),
  [Op.CALLDATASIZE]: op(Op.CALLDATASIZE, [], [Size]),
  [Op.CALLDATACOPY]: op(Op.CALLDATACOPY, [Locn, Locn, Size], []),
  [Op.CODESIZE]: op(Op.CODESIZE, [], [Size]),
  [Op.CODECOPY]: op(Op.CODECOPY, [Locn, Locn, Size], []),
  [Op.GASPRICE]: op(Op.GASPRICE, [], [Weis]),
  [Op.EXTCODESIZE]: op(Op.EXTCODESIZE, [Addr], [Size]),
  [Op.EXTCODECOPY]: op(Op.EXTCODECOPY, [Addr, Locn, Locn, Size], []),
  [Op.RETURNDATASIZE]: op(Op.RETURNDATASIZE, [], [Size]),
  [Op.RETURNDATACOPY]: op(Op.RETURNDATACOPY, [Locn, Locn, Size], []),
  [Op.EXTCODEHASH]: op(Op.EXTCODEHASH, [Addr], [Data]),
  [Op.BLOCKHASH]: op(Op.BLOCKHASH, [Uint], [Data]),
  [Op.COINBASE]: op(Op.COINBASE, [], [Addr]),
  [Op.TIMESTAMP]: op(Op.TIMESTAMP, [], [Uint]),
  [Op.NUMBER]: op(Op.NUMBER, [], [Uint]),
  [Op.DIFFICULTY]: op(Op.DIFFICULTY, [], [Uint]),
  [Op.GASLIMIT]: op(Op.GASLIMIT, [], [Uint]),
  [Op.CHAINID]: op(Op.CHAINID, [], [Uint]),
  [Op.SELFBALANCE]: op(Op.SELFBALANCE, [], [Weis]),
  [Op.BASEFEE]: op(Op.BASEFEE, [], [Weis]),
  [Op.BLOBHASH]: op(Op.BLOBHASH, [Uint], [Data]),
  [Op.BLOBBASEFEE]: op(Op.BLOBBASEFEE, [], [Weis]),
  [Op.POP]: op(Op.POP, [Word], []),
  [Op.MLOAD]: op(Op.MLOAD, [Locn], [Data]),
  [Op.MSTORE]: op(Op.MSTORE, [Locn, Data], []),
  [Op.MSTORE8]: op(Op.MSTORE8, [Locn, Data], []),
  [Op.SLOAD]: op(Op.SLOAD, [Data], [Data]),
  [Op.SSTORE]: op(Op.SSTORE, [Data, Data], []),
  [Op.JUMP]: op(Op.JUMP, [Locn], []),
  [Op.JUMPI]: op(Op.JUMPI, [Locn, Bool], []),
  [Op.PC]: op(Op.PC, [], [Locn]),
  [Op.MSIZE]: op(Op.MSIZE, [], [Size]),
  [Op.GAS]: op(Op.GAS, [], [Uint]),
  [Op.JUMPDEST]: op(Op.JUMPDEST, [], []),
  [Op.TLOAD]: op(Op.TLOAD, [Data], [Data]),
  [Op.TSTORE]: op(Op.TSTORE, [Data, Data], []),
  [Op.MCOPY]: op(Op.MCOPY, [Locn, Locn, Size], []),
  [Op.PUSH0]: op(Op.PUSH0, [], [Data]),
  [Op.PUSH1]: op(Op.PUSH1, [], [Data]),
  [Op.PUSH2]: op(Op.PUSH2, [], [Data]),
  [Op.PUSH3]: op(Op.PUSH3, [], [Data]),
  [Op.PUSH20]: op(Op.PUSH20, [], [Data]),
  [Op.PUSH32]: op(Op.PUSH32, [], [Data]),
  [Op.LOG0]: op(Op.LOG0, [Locn, Size], []),
  [Op.LOG1]: op(Op.LOG1, [Locn, Size, Data], []),
  [Op.LOG2]: op(Op.LOG2, [Locn, Size, Data, Data], []),
  [Op.LOG3]: op(Op.LOG3, [Locn, Size, Data, Data, Data], []),
  [Op.LOG4]: op(Op.LOG4, [Locn, Size, Data, Data, Data, Data], []),
  [Op.CREATE]: op(Op.CREATE, [Weis, Locn, Size], [Addr]),
  [Op.CALL]: op(Op.CALL,
    [Uint, Addr, Weis, Locn, Size, Locn, Size], [Bool]),
  [Op.RETURN]: op(Op.RETURN, [Locn, Size], null),
  [Op.DELEGATECALL]: op(Op.DELEGATECALL,
    [Uint, Addr, Locn, Size, Locn, Size], [Bool]),
  [Op.CREATE2]: op(Op.CREATE2, [Weis, Locn, Size, Data], [Addr]),
  [Op.REVERT]: op(Op.REVERT, [Locn, Size], null),
  [Op.SELFDESTRUCT]: op(Op.SELFDESTRUCT, [Addr], null),
};

export { Ops };
