import { Op } from "./opcodes";
import {
  Addr,
  Bool,
  Fragment,
  Locn,
  Size,
  Weis,
  Word,
} from "./types";

const Ops: Partial<Record<Op, Fragment>> = {
  [Op.STOP]: new Fragment([], [], 0, [Op.STOP]),
  [Op.ADD]: new Fragment([Word, Word], [Word], 2, [Op.ADD]),
  [Op.MUL]: new Fragment([Word, Word], [Word], 2, [Op.MUL]),
  [Op.SUB]: new Fragment([Word, Word], [Word], 2, [Op.SUB]),
  [Op.DIV]: new Fragment([Word, Word], [Word], 2, [Op.DIV]),
  [Op.SDIV]: new Fragment([Word, Word], [Word], 2, [Op.SDIV]),
  [Op.MOD]: new Fragment([Word, Word], [Word], 2, [Op.MOD]),
  [Op.SMOD]: new Fragment([Word, Word], [Word], 2, [Op.SMOD]),
  [Op.ADDMOD]: new Fragment([Word, Word, Word], [Word], 3, [Op.ADDMOD]),
  [Op.MULMOD]: new Fragment([Word, Word, Word], [Word], 3, [Op.MULMOD]),
  [Op.SIGNEXTEND]: new Fragment([Word, Word], [Word], 2, [Op.SIGNEXTEND]),
  [Op.LT]: new Fragment([Word, Word], [Bool], 2, [Op.LT]),
  [Op.GT]: new Fragment([Word, Word], [Bool], 2, [Op.GT]),
  [Op.SLT]: new Fragment([Word, Word], [Bool], 2, [Op.SLT]),
  [Op.SGT]: new Fragment([Word, Word], [Bool], 2, [Op.SGT]),
  [Op.EQ]: new Fragment([Word, Word], [Bool], 2, [Op.EQ]),
  [Op.ISZERO]: new Fragment([Word], [Bool], 1, [Op.ISZERO]),
  [Op.AND]: new Fragment([Word, Word], [Word], 2, [Op.AND]),
  [Op.OR]: new Fragment([Word, Word], [Word], 2, [Op.OR]),
  [Op.XOR]: new Fragment([Word, Word], [Word], 2, [Op.XOR]),
  [Op.NOT]: new Fragment([Word], [Word], 1, [Op.NOT]),
  [Op.BYTE]: new Fragment([Word, Word], [Word], 2, [Op.BYTE]),
  [Op.SHL]: new Fragment([Word, Word], [Word], 2, [Op.SHL]),
  [Op.SHR]: new Fragment([Word, Word], [Word], 2, [Op.SHR]),
  [Op.SAR]: new Fragment([Word, Word], [Word], 2, [Op.SAR]),
  [Op.SHA3]: new Fragment([Locn, Size], [Word], 2, [Op.SHA3]),
  [Op.ADDRESS]: new Fragment([], [Addr], 0, [Op.ADDRESS]),
  [Op.BALANCE]: new Fragment([Addr], [Weis], 1, [Op.BALANCE]),
  [Op.ORIGIN]: new Fragment([], [Addr], 0, [Op.ORIGIN]),
  [Op.CALLER]: new Fragment([], [Addr], 0, [Op.CALLER]),
  [Op.CALLVALUE]: new Fragment([], [Weis], 0, [Op.CALLVALUE]),
  [Op.CALLDATALOAD]: new Fragment([Locn], [Word], 1, [Op.CALLDATALOAD]),
  [Op.CALLDATASIZE]: new Fragment([], [Size], 0, [Op.CALLDATASIZE]),
  [Op.CALLDATACOPY]: new Fragment([Locn, Locn, Size], [], 3, [Op.CALLDATACOPY]),
  [Op.CODESIZE]: new Fragment([], [Size], 0, [Op.CODESIZE]),
  [Op.CODECOPY]: new Fragment([Locn, Locn, Size], [], 3, [Op.CODECOPY]),
  [Op.GASPRICE]: new Fragment([], [Word], 0, [Op.GASPRICE]),
  [Op.EXTCODESIZE]: new Fragment([Addr], [Size], 1, [Op.EXTCODESIZE]),
  [Op.EXTCODECOPY]: new Fragment(
    [Addr, Locn, Locn, Size], [], 4, [Op.EXTCODECOPY]),
  [Op.RETURNDATASIZE]: new Fragment([], [Size], 0, [Op.RETURNDATASIZE]),
  [Op.RETURNDATACOPY]: new Fragment(
    [Locn, Locn, Size], [], 3, [Op.RETURNDATACOPY]),
  [Op.EXTCODEHASH]: new Fragment([Addr], [Word], 1, [Op.EXTCODEHASH]),
  [Op.BLOCKHASH]: new Fragment([Word], [Word], 1, [Op.BLOCKHASH]),
  [Op.COINBASE]: new Fragment([], [Addr], 0, [Op.COINBASE]),
  [Op.TIMESTAMP]: new Fragment([], [Word], 0, [Op.TIMESTAMP]),
  [Op.NUMBER]: new Fragment([], [Word], 0, [Op.NUMBER]),
  [Op.DIFFICULTY]: new Fragment([], [Word], 0, [Op.DIFFICULTY]),
  [Op.GASLIMIT]: new Fragment([], [Word], 0, [Op.GASLIMIT]),
  [Op.CHAINID]: new Fragment([], [Word], 0, [Op.CHAINID]),
  [Op.SELFBALANCE]: new Fragment([], [Weis], 0, [Op.SELFBALANCE]),
  [Op.BASEFEE]: new Fragment([], [Weis], 0, [Op.BASEFEE]),
  [Op.BLOBHASH]: new Fragment([Word], [Word], 1, [Op.BLOBHASH]),
  [Op.BLOBBASEFEE]: new Fragment([], [Word], 0, [Op.BLOBBASEFEE]),
  [Op.POP]: new Fragment([Word], [], 1, [Op.POP]),
  [Op.MLOAD]: new Fragment([Locn], [Word], 1, [Op.MLOAD]),
  [Op.MSTORE]: new Fragment([Locn, Word], [], 2, [Op.MSTORE]),
  [Op.MSTORE8]: new Fragment([Locn, Word], [], 2, [Op.MSTORE8]),
  [Op.SLOAD]: new Fragment([Locn], [Word], 1, [Op.SLOAD]),
  [Op.SSTORE]: new Fragment([Locn, Word], [], 2, [Op.SSTORE]),
  [Op.JUMP]: new Fragment([Locn], [], 1, [Op.JUMP]),
  [Op.JUMPI]: new Fragment([Locn, Bool], [], 2, [Op.JUMPI]),
  [Op.PC]: new Fragment([], [Locn], 0, [Op.PC]),
  [Op.MSIZE]: new Fragment([], [Size], 0, [Op.MSIZE]),
  [Op.GAS]: new Fragment([], [Word], 0, [Op.GAS]),
  [Op.JUMPDEST]: new Fragment([], [], 0, [Op.JUMPDEST]),
  [Op.TLOAD]: new Fragment([Word], [Word], 1, [Op.TLOAD]),
  [Op.TSTORE]: new Fragment([Word, Word], [], 2, [Op.TSTORE]),
  [Op.MCOPY]: new Fragment([Locn, Locn, Size], [], 3, [Op.MCOPY]),
  [Op.PUSH0]: new Fragment([], [Word], 0, [Op.PUSH0]),
  [Op.PUSH1]: new Fragment([], [Word], 0, [Op.PUSH1]),
  [Op.PUSH2]: new Fragment([], [Word], 0, [Op.PUSH2]),
  [Op.PUSH3]: new Fragment([], [Word], 0, [Op.PUSH3]),
  [Op.PUSH20]: new Fragment([], [Word], 0, [Op.PUSH20]),
  [Op.PUSH32]: new Fragment([], [Word], 0, [Op.PUSH32]),
  [Op.LOG0]: new Fragment([Locn, Size], [], 2, [Op.LOG0]),
  [Op.LOG1]: new Fragment([Locn, Size, Word], [], 3, [Op.LOG1]),
  [Op.LOG2]: new Fragment([Locn, Size, Word, Word], [], 4, [Op.LOG2]),
  [Op.LOG3]: new Fragment([Locn, Size, Word, Word, Word], [], 5, [Op.LOG3]),
  [Op.LOG4]: new Fragment(
    [Locn, Size, Word, Word, Word, Word], [], 6, [Op.LOG4]),
  [Op.CREATE]: new Fragment([Weis, Locn, Size], [Addr], 3, [Op.CREATE]),
  [Op.CALL]: new Fragment(
    [Word, Addr, Weis, Locn, Size, Locn, Size], [Bool], 7, [Op.CALL]),
  [Op.RETURN]: new Fragment([Locn, Size], [], 2, [Op.RETURN]),
  [Op.DELEGATECALL]: new Fragment(
    [Word, Addr, Locn, Size, Locn, Size], [Bool], 6, [Op.DELEGATECALL]),
  [Op.CREATE2]: new Fragment([Weis, Locn, Size, Word], [Addr], 4, [Op.CREATE2]),
  [Op.REVERT]: new Fragment([Locn, Size], [], 2, [Op.REVERT]),
  [Op.SELFDESTRUCT]: new Fragment([Addr], [], 1, [Op.SELFDESTRUCT]),
};

export { Ops };
