import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join, relative, resolve } from "node:path";
import process from "node:process";
import css from "./transpiler/css";

const IgnoredDirs = new Set([
  ".git",
  ".kdjs_isolate",
  "build",
  "node_modules"
]);

const IdentityMapper = {
  map(_namespace, _context, domId) {
    return domId;
  },
  preserve(_namespace, domId) {
    return domId;
  }
};

const getDeclarationPath = (filePath) =>
  `${filePath.slice(0, -".css".length)}.d.css.ts`;

const getDeclaration = (filePath, content) => {
  // The concrete minified values depend on the build's shared GlobalMapper
  // state, so the stable part we can safely expose to tsserver is the
  // property set, not the final string literal.
  const { enumEntries } = css.minify(filePath, content, IdentityMapper);
  const keys = Object.keys(enumEntries).sort();

  let declaration = "// Generated by `bun run css-types`. Do not edit by hand.\n\n";
  declaration += "declare const Css: KastroStyleSheetComponent";

  if (keys.length) {
    declaration += " & {\n";
    for (const key of keys)
      declaration += `  readonly ${JSON.stringify(key)}: string;\n`;
    declaration += "}";
  }

  declaration += ";\n\nexport default Css;\n";
  return declaration;
};

const writeDeclaration = async (rootDir, cssPath) => {
  const content = await readFile(cssPath, "utf8");
  const relativePath = relative(rootDir, cssPath);
  const declaration = getDeclaration(relativePath, content);
  const declarationPath = resolve(rootDir, "build", getDeclarationPath(relativePath));

  await mkdir(dirname(declarationPath), { recursive: true });
  await writeFile(declarationPath, declaration);
  return relative(rootDir, declarationPath);
};

const collectCssFiles = async (dirPath) => {
  const entries = await readdir(dirPath, { withFileTypes: true });
  /** @type {string[]} */
  const cssFiles = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (!IgnoredDirs.has(entry.name))
        cssFiles.push(...await collectCssFiles(join(dirPath, entry.name)));
      continue;
    }

    if (entry.isFile() && extname(entry.name) == ".css")
      cssFiles.push(join(dirPath, entry.name));
  }

  return cssFiles;
};

const rootDir = process.cwd();
const inputPaths = process.argv.slice(2).map((inputPath) => resolve(rootDir, inputPath));
const cssFiles = inputPaths.length
  ? inputPaths.filter((filePath) => extname(filePath) == ".css")
  : await collectCssFiles(rootDir);

cssFiles.sort();

for (const cssPath of cssFiles) {
  const writtenPath = await writeDeclaration(rootDir, cssPath);
  console.log(`wrote ${writtenPath}`);
}
