import { compile } from "../../kdc/compile";

export default [
  compile({
    inputs: [
      "did/test/decryptedSections.compiled-test.js",
      "crosschain/mock/signer.js",
      "crosschain/signer.js", "crosschain/unlockable.js",
      "crosschain/unlockable.d.js",
      "crypto/modular.js",
      "crypto/primes.js",
      "crypto/secp256k1.js",
      "crypto/sha3.js",
      "crypto/wesolowski.js",
      "did/decryptedSections.d.js",
      "did/decryptedSections.js",
      "did/KPassData.d.js",
      "did/section.d.js",
      "did/section.js",
      "did/verifiableID.d.js",
      "did/verifiableID.js",
      "ethereum/encryptedData.d.js",
      "ethereum/ERC721Unlockable.d.js",
      "ethereum/eth.d.js",
      "ethereum/evm.js",
      "kdc/externs/nodejs.d.js",
      "node/nvi.d.js",
      "testing/assert.js",
      "testing/vm.js",
      "util/çevir.js",
    ],
    output: "build/did/test/decryptedSections.compiled-test.js"
  }),
  compile({
    inputs: [
      "did/test/section.compiled-test.js",
      "crosschain/unlockable.d.js",
      "crosschain/unlockable.js",
      "crypto/modular.js",
      "crypto/secp256k1.js",
      "crypto/sha3.js",
      "did/decryptedSections.d.js",
      "did/KPassData.d.js",
      "did/section.d.js",
      "did/section.js",
      "did/verifiableID.d.js",
      "ethereum/encryptedData.d.js",
      "ethereum/eth.d.js",
      "ethereum/evm.js",
      "kdc/externs/nodejs.d.js",
      "node/nvi.d.js",
      "testing/assert.js",
      "testing/vm.js",
      "util/çevir.js",
    ],
    output: "build/did/test/section.compiled-test.js"
  }),
  compile({
    inputs: [
      "did/test/verifiableID.compiled-test.js",
      "crosschain/unlockable.d.js",
      "crosschain/unlockable.js",
      "crypto/modular.js",
      "crypto/primes.js",
      "crypto/sha3.js",
      "crypto/wesolowski.js",
      "did/decryptedSections.d.js",
      "did/KPassData.d.js",
      "did/section.d.js",
      "did/verifiableID.d.js",
      "did/verifiableID.js",
      "ethereum/encryptedData.d.js",
      "ethereum/eth.d.js",
      "ethereum/evm.js",
      "kdc/externs/nodejs.d.js",
      "node/nvi.d.js",
      "testing/assert.js",
      "util/çevir.js",
    ],
    output: "build/did/test/verifiableID.compiled-test.js"
  })
];
