name: All benchmarks

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  benchmark_bun:
    name: Micro benches with bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - name: Run crypto benchmarks
        run: |
          bun i
          bun run.js bench
