name: Bench

on:
  push:
    branches: ["ana", "main"]
  pull_request:
    branches: ["ana", "main"]

jobs:
  benchmark_crypto:
    name: crypto benches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: echo "$GITHUB_WORKSPACE/node_modules/.bin" >> "$GITHUB_PATH"
      - name: Run crypto benchmarks
        run: kdts bench crypto --strict
  benchmark_util:
    name: util benches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: echo "$GITHUB_WORKSPACE/node_modules/.bin" >> "$GITHUB_PATH"
      - name: Run util benchmarks
        run: kdts bench util --strict
