name: Test

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  bun_unit_tests:
    name: bun unit tests
    runs-on: ubuntu-latest
    env:
      CF_TESTING_ACCOUNT_ID: ${{ secrets.CF_TESTING_ACCOUNT_ID }}
      CF_TESTING_API_TOKEN: ${{ secrets.CF_TESTING_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i
          bun test

  kdjs_fast_unit_tests:
    name: kdjs fast unit tests
    runs-on: ubuntu-latest
    env:
      CF_TESTING_ACCOUNT_ID: ${{ secrets.CF_TESTING_ACCOUNT_ID }}
      CF_TESTING_API_TOKEN: ${{ secrets.CF_TESTING_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i
          bun run test --fast

  kdjs_unit_tests_api:
    name: kdjs unit tests, api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun run test api --strict

  kdjs_unit_tests_crosschain:
    name: kdjs unit tests, crosschain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun run test crosschain --strict

  kdjs_unit_tests_crypto:
    name: kdjs unit tests, crypto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun run test crypto --strict

  kdjs_unit_tests_did:
    name: kdjs unit tests, did
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun run test did --strict

  kdjs_unit_tests_ethereum:
    name: kdjs unit tests, ethereum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun run test ethereum

  kdjs_unit_tests_kastro:
    name: kdjs unit tests, kastro
    runs-on: ubuntu-latest
    env:
      CF_TESTING_ACCOUNT_ID: ${{ secrets.CF_TESTING_ACCOUNT_ID }}
      CF_TESTING_API_TOKEN: ${{ secrets.CF_TESTING_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun run test kastro

  kdjs_unit_tests_kdjs:
    name: kdjs unit tests, kdjs
    runs-on: ubuntu-latest
    if: false # Temporarily disabled
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun run test kdjs

  kdjs_unit_tests_mina:
    name: kdjs unit tests, mina
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun run test mina --strict

  kdjs_unit_tests_protocol:
    name: kdjs unit tests, protocol
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun run test protocol

  kdjs_unit_tests_util:
    name: kdjs unit tests, util
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun run test util

  compile_kdjs_with_kdjs:
    name: Compile `kdjs` with `kdjs`
    runs-on: ubuntu-latest
    if: false # Temporarily disabled
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - run: |
          bun i
          bun kdjs/kdjs.js kdjs/kdjs.js
