name: Test

on:
  push:
    branches: ["ana", "prod"]
  pull_request:
    branches: ["ana", "prod"]

jobs:
  bun_unit_tests:
    name: bun unit tests
    runs-on: ubuntu-latest
    env:
      CF_TESTING_ACCOUNT_ID: ${{ secrets.CF_TESTING_ACCOUNT_ID }}
      CF_TESTING_API_TOKEN: ${{ secrets.CF_TESTING_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i
          bun test

  kdjs_unit_tests_crypto:
    name: kdjs unit tests, crypto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i
          bun run test crypto

  kdjs_unit_tests_did:
    name: kdjs unit tests, did
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i
          bun run test did

  kdjs_unit_tests_kastro:
    name: kdjs unit tests, kastro
    runs-on: ubuntu-latest
    env:
      CF_TESTING_ACCOUNT_ID: ${{ secrets.CF_TESTING_ACCOUNT_ID }}
      CF_TESTING_API_TOKEN: ${{ secrets.CF_TESTING_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i
          bun run test kastro

  kdjs_unit_tests_others:
    name: kdjs unit tests, others
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i
          bun run test --filter did crypto kastro

  compile_kdjs_with_kdjs:
    name: Compile `kdjs` with `kdjs`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i
          bun kdjs/kdjs.js kdjs/kdjs.js
